#define DFU_APP_START 0x08000000 + 1024 * 4
#define DFU_INTF_EEPROM _DISABLE

// RDP level DANGER!
#define DFU_SEAL_LEVEL 1

#define DFU_VERIFY_CHECKSUM CRC32FAST
#define DFU_CIPHER DFU_CIPHER_CHACHA_A
#define DFU_AES_IV_96 ACT_SECRET_IV
#define DFU_AES_KEY_256 ACT_SECRET_KEY

#define DFU_DNLOAD_NOSYNC _ENABLE
#define DFU_CAN_UPLOAD _DISABLE
#define DFU_DETACH _ENABLE

#define DFU_VENDOR_ID 0x0483
#define DFU_DEVICE_ID 0xDF11
#define DFU_STR_MANUF "onii-mai"
#define DFU_STR_PRODUCT "onii-mai bootloader"
#define DFU_DSC_CONFIG _ENABLE
#define DFU_STR_CONFIG "DFU"
#define DFU_WCID _ENABLE

#define DFU_BOOTSTRAP_GPIO GPIOB
#define DFU_BOOTSTRAP_PIN 8
#define DFU_BOOTSTRAP_LEVEL _LOW
#define LED_GPIO  GPIOC_BASE
#define LED_PIN   12
